# Generated by Django 3.2.8 on 2021-10-08 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_word', models.CharField(max_length=255)),
                ('pronounciation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(blank=True, choices=[('noun', 'Kata Benda'), ('pronoun', 'Kata Ganti'), ('verb', 'Kata Kerja'), ('adjective', 'Kata Sifat'), ('adverb', 'Kata Keterangan'), ('preposition', 'Kata Depan'), ('conjunction', 'Kata Hubung'), ('interjection', 'Kata Seru')], max_length=20, null=True)),
                ('meaning', models.CharField(max_length=1024)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word', to='word.word')),
            ],
        ),
    ]
