# Generated by Django 3.2.8 on 2021-10-08 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meaning', to='word.word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='base_word',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronounciation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
