# Generated by Django 3.2.8 on 2021-10-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_auto_20211008_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='meaning',
            name='pos_verbose',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
