# Generated by Django 3.2.8 on 2021-10-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_meaning_pos_verbose'),
    ]

    operations = [
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('verbose', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='meaning',
            name='pos_verbose',
        ),
        migrations.AlterField(
            model_name='meaning',
            name='meaning',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.RemoveField(
            model_name='meaning',
            name='pos',
        ),
        migrations.AddField(
            model_name='meaning',
            name='pos',
            field=models.ManyToManyField(blank=True, related_name='meaning', to='word.POS'),
        ),
    ]
